[tool.poetry]
name = "tap-dv360"
version = "0.0.1"
description = "Singer tap for dv360, built with the Meltano Singer SDK."
readme = "README.md"
authors = ["peter wang <pw33537515@gmail.com>"]
keywords = ["ELT", "dv360"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.9"
singer-sdk = { version="~=0.44.3", extras = ["faker"] }
requests = "~=2.32.3"
google-auth = "*"
google-auth-oauthlib = "*"

[tool.ruff.lint.pydocstyle]
convention = "google"





[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
tap-dv360 = 'tap_dv360.tap:Tapdv360.cli'
